"""Serialise Python data structures into OpenFOAM dictionary files."""
from __future__ import annotations

from pathlib import Path
from typing import Any

HEADER = """/*--------------------------------*- C++ -*----------------------------------*\\
| =========                 |                                                 |
| \\\\      /  F ield         | OpenFOAM: generated by XFoilFOAM                |
|  \\\\    /   O peration     |                                                 |
|   \\\\  /    A nd           |                                                 |
|    \\\\/     M anipulation  |                                                 |
\\*---------------------------------------------------------------------------*/
"""


class Raw(str):
    """A value emitted verbatim (no quoting / formatting), e.g. dimensions or expressions."""


class Verbatim:
    """Wraps a pre-rendered block of OpenFOAM text inserted as-is for a key."""

    def __init__(self, text: str):
        self.text = text


def dimensions(*dims: int) -> Raw:
    return Raw("[" + " ".join(str(d) for d in dims) + "]")


def vector(x: float, y: float, z: float) -> Raw:
    return Raw(f"({_num(x)} {_num(y)} {_num(z)})")


def _num(v: float) -> str:
    if isinstance(v, bool):  # pragma: no cover - guarded by callers
        return "true" if v else "false"
    if isinstance(v, int):
        return str(v)
    f = float(v)
    if f == int(f) and abs(f) < 1e15:
        return str(int(f))
    return repr(f)


def _format_value(value: Any) -> str:
    if isinstance(value, Raw):
        return str(value)
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (int, float)):
        return _num(value)
    if isinstance(value, str):
        return value
    if isinstance(value, (list, tuple)):
        return "(" + " ".join(_format_value(v) for v in value) + ")"
    raise TypeError(f"Cannot format value of type {type(value)!r}")


def _render_entries(entries: dict[str, Any], indent: int) -> list[str]:
    pad = " " * indent
    lines: list[str] = []
    for key, value in entries.items():
        if isinstance(value, Verbatim):
            block = value.text.rstrip("\n")
            lines.append(f"{pad}{key}")
            lines.append(f"{pad}{{")
            for ln in block.splitlines():
                lines.append(f"{pad}    {ln}")
            lines.append(f"{pad}}}")
        elif isinstance(value, dict):
            lines.append(f"{pad}{key}")
            lines.append(f"{pad}{{")
            lines.extend(_render_entries(value, indent + 4))
            lines.append(f"{pad}}}")
        else:
            lines.append(f"{pad}{key:<15} {_format_value(value)};")
    return lines


def foam_file_header(class_name: str, object_name: str, location: str | None = None) -> str:
    loc = f'\n    location    "{location}";' if location else ""
    return (
        HEADER
        + "FoamFile\n{\n"
        + "    version     2.0;\n"
        + "    format      ascii;\n"
        + f"    class       {class_name};{loc}\n"
        + f"    object      {object_name};\n"
        + "}\n"
        + "// * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * //\n"
    )


def write_foam_dict(
    path: Path,
    class_name: str,
    object_name: str,
    entries: dict[str, Any],
    location: str | None = None,
) -> None:
    """Write a complete OpenFOAM dictionary file."""
    path.parent.mkdir(parents=True, exist_ok=True)
    body = "\n".join(_render_entries(entries, 0))
    text = foam_file_header(class_name, object_name, location) + "\n" + body + "\n"
    path.write_text(text)


def render_field(
    class_name: str,
    object_name: str,
    dims: Raw,
    internal_field: str,
    boundary_field: dict[str, Any],
) -> str:
    """Render a 0/ field file (volScalarField / volVectorField)."""
    header = foam_file_header(class_name, object_name, "0")
    lines = [header, ""]
    lines.append(f"dimensions      {dims};")
    lines.append("")
    lines.append(f"internalField   {internal_field};")
    lines.append("")
    lines.append("boundaryField")
    lines.append("{")
    lines.extend(_render_entries(boundary_field, 4))
    lines.append("}")
    return "\n".join(lines) + "\n"
